### ISSUE TITLE
upload to stackage

### ISSUE THREAD

**Issue by stites** [tensorflow/haskell#117]
Now that the tensorflow-* libraries are on hackage and run on lts-8.13, it would be excellent to have them uploaded to stackage as well: https://github.com/fpco/stackage/#add-your-package

**Comment by judah** [comment]
Opened fpco/stackage#2517.

**Comment by stites** [comment]
It just got merged! closing this now.

**Comment by judah** [comment]
Update: the packages (excluding `tensorflow-{logging,records,records-conduit}`) are now in Stackage nightly:
https://www.stackage.org/nightly-2017-05-20/package/tensorflow-0.1.0.2
