### ISSUE TITLE
have tests run on pull requests

### ISSUE THREAD

**Issue by silky** [tensorflow/haskell#12]
it would be good if there was a CI set up so that all PRs could be tested.

**Comment by blackgnezdo** [comment]
So true! We want to set something up with Jenkins, like the rest of TensorFlow has. @gunan maybe you can help us get started?

**Comment by gunan** [comment]
Let me consult a few people here to see where we can run tests on this repo.
I will assign the issue myself to not forget.

**Comment by gunan** [comment]
I cannot seem to assign the issue :)
I will update here with more information.

**Comment by gunan** [comment]
OK, I can help you get some tests running on ci.tensorflow.org
You simply need to give me a bash script I need to run, Then I will setup the continuous build on master.

Then we need to setup some webhooks. We need a repository administrator to do that.
I can also do this wiring if you give me temporary access.

**Comment by blackgnezdo** [comment]
I imagine the easiest would be for us to have a canonical docker image which rebuilds everything including TF? Something akin to Mac OS build instructions in our README.md? Once I have this checked in we can ask @martinwicke to grant the necessary permissions to @gunan. I'm taking over this issue to do the first step.

**Comment by gunan** [comment]
If you only would like a build, it is OK.
However, if you actually have some tests that need to be run, that would be even better.
One other option is to:
- fetch the latest TF docker image, 
- start a container with this image
- inside that container run a script that builds and tests haskell bindings.

I think this would be even faster to run as we avoid building full TF.

**Comment by blackgnezdo** [comment]
We do have the tests. But I don't know if there's an option to communicate individual test status beyond a simple exit code from the script. Probably not really what you had in mind @gunan? One thing about using a "raw" TF container is we have a pretty heavy build dependencies that would be nice to cache (the compiler and all the dependent libraries).

**Comment by gunan** [comment]
I see, then how about building a new Docker image on top of TF docker?
Like how we do on top of nvidia/cuda
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/Dockerfile.gpu#L1
I am just trying to get you a faster test by avoiding rebuild of TF.

For the test script, are these bazel tests?
We have some bash scripts to run and capture all test outputs, maybe we can prepare something like that for this repo too?

**Comment by blackgnezdo** [comment]
They are not bazel tests (pragmatic reasons). Pattern matching should be easy, but let's cross that bridge later.

**Comment by blackgnezdo** [comment]
#14 has the script: ./ci_build/outer_launch_tests.sh
