### ISSUE TITLE
Native installation on Linux (Fedora)?

### ISSUE THREAD

**Issue by skeydan** [tensorflow/haskell#133]
Hi,

I see you have installation instructions either using docker or native MacOS X - is a native install on Linux distros supported, too? And would you happen to have instructions for that?

Many thanks
Sigrid

**Comment by blackgnezdo** [comment]
I don't know of anybody spending much time with this project using Fedora. You are welcome to send a PR with such instructions. We won't be able to verify them, so please mention that they are "maintained by @skeydan".

**Comment by judah** [comment]
The Dockerfile itself basically gives the necessary instructions for doing a native install on Ubuntu:
https://github.com/tensorflow/haskell/blob/master/docker/Dockerfile#L24
The steps for Fedora are probably similar.

**Comment by skeydan** [comment]
OK thank you! The ubuntu installation really should help!
I'll let you know as soon as I've gotten around to try it out.
