### ISSUE TITLE
Failed to load interface for ‘TensorFlow.Minimize’

### ISSUE THREAD

**Issue by lgastako** [tensorflow/haskell#137]
I created a new project via `stack new tensorshell` and then added the `tensorflow-*` libraries to `stack.yaml` and the `tensorshell.cabal` file in hopes of being able to run the [example program from the README](https://github.com/tensorflow/haskell/blob/master/README.md) which I pasted in unchanged as [RegTest.hs here](https://github.com/lgastako/tensorshell/blob/master/src/RegTest.hs).

The project and dependencies build and install but compiling `RegTest.hs` gives me:

    src/RegTest.hs:9:1-45: error: …
        Failed to load interface for ‘TensorFlow.Minimize’
        Use -v to see a list of the files searched for.
    Compilation failed.

And I can't autocomplete `Tensor.M...` in GHCI.  I can see that [Minimize.hs is here] in `master` but not in  `release-1.0.2`.  I tried changing the reference in stack.yaml to point to a local checkout of `master` but then I get:

    Preprocessing library tensorflow-ops-0.1.0.0...
    [1 of 7] Compiling TensorFlow.Queue ( src/TensorFlow/Queue.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/TensorFlow/Queue.o )
    [2 of 7] Compiling TensorFlow.Ops   ( src/TensorFlow/Ops.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/TensorFlow/Ops.o )

    /Users/john/src/tensorflow-haskell/tensorflow-ops/src/TensorFlow/Ops.hs:249:67: error:
        • Could not deduce (Rendered v)
            arising from a use of ‘renderedOutput’
          from the context: (Rendered (Tensor v), MonadBuild m, TensorType a)
            bound by the type signature for:
                       save :: (Rendered (Tensor v), MonadBuild m, TensorType a) =>
                               ByteString -> [Tensor v a] -> m ControlNode
            at src/TensorFlow/Ops.hs:(244,1)-(247,24)
          Possible fix:
            add (Rendered v) to the context of
              the inferred type of
              toByteStringTensor :: Tensor v a1 -> Tensor Build ByteString
              or the type signature for:
                   save :: (Rendered (Tensor v), MonadBuild m, TensorType a) =>
                           ByteString -> [Tensor v a] -> m ControlNode
        • In the second argument of ‘(.)’, namely ‘renderedOutput’
          In the second argument of ‘(.)’, namely
            ‘encodeOutput . renderedOutput’
          In the second argument of ‘(.)’, namely
            ‘encodeUtf8 . encodeOutput . renderedOutput’

    --  While building package tensorflow-ops-0.1.0.0 using:
          /Users/john/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.24.2.0 build lib:tensorflow-ops --ghc-options " -ddump-hi -ddump-to-file"
        Process exited with code: ExitFailure 1

Presumably because some versions of the other tensorflow packages are now out of sync with `master`.  Is there a known good combination that I can use to get the example working in GHCI (and ultimately hopefully in IHaskell)? 

Thanks.

**Comment by judah** [comment]
Apologies for the confusion.  As you guessed, the Readme currently references the latest version of the code in GitHub, not the versions released on Hackage.  That discrepancy should go away with the next release of this package; though we still ought to figure out a better long-term solution for such documentation.

You have two options:

- Use the release on Hackage with older instructions as described [here](https://github.com/tensorflow/haskell/blob/d62c61469558cc089ef461bfcf412b9579eaaacc/README.md)
-  `git clone --recursive` this repository to get the latest (master) version, and then follow the newer Readme instructions.

Please let us know whether that works for you.

**Comment by lgastako** [comment]
I was able to get the latest master version working after a recursive clone.  Thanks.
