### ISSUE TITLE
parseAttrType: unrecognized type "func" for op "FilterDataset" when compiling tensorflow-core-ops-0.1.0.0 

### ISSUE THREAD

**Issue by schernichkin** [tensorflow/haskell#140]
Probably version-related issue, I got this message while trying to compile with tensorflow 1.2.0. In this case library should check tensorflow version or supported version should be mentioned in library description.

**Comment by fkm3** [comment]
Yeah, it looks like a tensorflow1.2 feature we don't support yet.

**Comment by blackgnezdo** [comment]
FWIW, we are explicit in the code about which [version of TF we are compatible with on OSX](https://github.com/tensorflow/haskell/blob/master/tools/install_osx_dependencies.sh#L28) and [on Linux](https://github.com/tensorflow/haskell/blob/master/docker/Dockerfile#L3).

Unfortunately this is not as helpful when using stack or hackage. Upgrade and documentation update PRs are encouraged :)

**Comment by judah** [comment]
It looks like we've already blacklisted one op from libtensorflow v1.0 for the same reason:
https://github.com/tensorflow/haskell/blob/master/tensorflow-core-ops/Setup.hs#L92
Might be worth proactively adding the new problem ops to the blacklist.  But regardless, I agree we should also document which version(s) of tensorflow we're compatible with.

**Comment by fkm3** [comment]
Closing this since we now support tensorflow 1.9.
