### ISSUE TITLE
tensorflow-core-ops build error

### ISSUE THREAD

**Issue by leptonyu** [tensorflow/haskell#148]
Hi,
  I tried to build tensorflow-core-ops 0.1.0.0 in LTS Haskell 9.1, came with the following build error? How can I solve this? libtensorflow version 1.3

--  While building package tensorflow-core-ops-0.1.0.0 using:
     /private/var/folders/_y/bh1tdq6s1dd9kz9wdxh1cbdm0000gr/T/stack79985/tensorflow-core-ops-0.1.0.0/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/setup/setup --builddir=.stack-work/dist/x86_64-osx/Cabal-1.24.2.0 build --ghc-options " -ddump-hi -ddump-to-file"
   Process exited with code: ExitFailure 1
   Logs have been written to: /Users/daniel/.stack/global-project/.stack-work/logs/tensorflow-core-ops-0.1.0.0.log

   [1 of 2] Compiling Main             ( /private/var/folders/_y/bh1tdq6s1dd9kz9wdxh1cbdm0000gr/T/stack79985/tensorflow-core-ops-0.1.0.0/Setup.hs, /private/var/folders/_y/bh1tdq6s1dd9kz9wdxh1cbdm0000gr/T/stack79985/tensorflow-core-ops-0.1.0.0/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/setup/Main.o )
   [2 of 2] Compiling StackSetupShim   ( /Users/daniel/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /private/var/folders/_y/bh1tdq6s1dd9kz9wdxh1cbdm0000gr/T/stack79985/tensorflow-core-ops-0.1.0.0/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/setup/StackSetupShim.o )
   Linking /private/var/folders/_y/bh1tdq6s1dd9kz9wdxh1cbdm0000gr/T/stack79985/tensorflow-core-ops-0.1.0.0/.stack-work/dist/x86_64-osx/Cabal-1.24.2.0/setup/setup ...
   Configuring tensorflow-core-ops-0.1.0.0...
   parseAttrType: unrecognized type "func" for op "FilterDataset"
   CallStack (from HasCallStack):
   error, called at src/TensorFlow/OpGen/ParsedOp.hs:342:10 in
   tensorflow-opgen-0.1.0.0-9gIM6DSJBcgE9HQZAwSLKX:TensorFlow.OpGen.ParsedOp

**Comment by fkm3** [comment]
Try adding "FilterDataset" to the blacklist in https://github.com/tensorflow/haskell/blob/7328cb277fd52f700d61b7e79ffb058e58d161f1/tensorflow-core-ops/Setup.hs#L93.

**Comment by ccressent** [comment]
Here is the full list of ops you need to blacklist in order to build `tensorflow-core-ops` with version 1.3 of the tensorflow library:

```
blackList =
    [ -- Requires the "func" type:
      "SymbolicGradient"
    , "FilterDataset"
    , "FlatMapDataset"
    , "GroupByWindowDataset"
    , "InterleaveDataset"
    , "MapDataset"
    , "OneShotIterator"
    , "ParallelMapDataset"
    ]
```

You will probably run into other issues down the line, so I would advise with sticking with version 1.0 of the tensorflow library for now!

**Comment by fkm3** [comment]
We support much newer versions of libtensorflow now, so the errors described here should be fixed.
