### ISSUE TITLE
Monad transformer version of Session

### ISSUE THREAD

**Issue by jbransen** [tensorflow/haskell#153]
It would be useful to have a `SessionT` as well, such that we can run the TensorFlow operations in any monad with a `MonadIO` instance instead of just `IO` itself.

**Comment by fkm3** [comment]
`Session` is just a monad transformer stack, so that should be straightforward to add if you are interested https://github.com/tensorflow/haskell/blob/master/tensorflow/src/TensorFlow/Session.hs#L76 in sending a PR.
