### ISSUE TITLE
git not on docker image results in inability to build

### ISSUE THREAD

**Issue by silky** [tensorflow/haskell#160]
i'm not quite sure why this doesn't seem to affect other people, but when i try and include this project as a package of another project, it fails when i build because git doesn't exist in the docker image

this is the error https://github.com/commercialhaskell/stack/issues/3196 (i reported it to stack a while ago, but they pointed out that it was "by design").

it would be good if we could put git into the standard docker image (`tensorflow/haskell:v0`) so that it can be included easily.

thoughts?

**Comment by blackgnezdo** [comment]
Could you mention the steps to reproduce the scenario which is no working? I'm a bit unclear about what's going on and so can't really figure out the best course of action.

**Comment by silky** [comment]
to repro, you should:

1. make a new project that includes tensorflow-haskell as another package to build,
2. use the docker image created by following the readme of this repo to build it

it will fail because the first thing it tries to do is clone the package defined in the stack yaml, but it can't, because the docker image doesn't contain the `git` executable

this is how i build my project here - https://github.com/silky/deep-scite/tree/haskell/deepscite-hs ( https://github.com/silky/deep-scite/blob/haskell/deepscite-hs/stack.yaml )

i guess arguably it's wrong of me to re-use the docker image for this project; i should probably just provide the docker file in my own project, and put git in it there (which is actually how i'm working around this at the moment ...)

it's probably a bad idea to add git into the dockerfile here, because it's not strictly needed. i'll close this issue, but i hope that explains what i was thinking.

**Comment by blackgnezdo** [comment]
The way you are doing it is very much in line with my understanding of how Docker is supposed to be used. You extend our image with your tools and use it. The change is an increment and if we were to publish our image somebody would be easily able to reuse it with your Dockerfile.
