### ISSUE TITLE
Installing the library on macOS

### ISSUE THREAD

**Issue by AlejandroCatalina** [tensorflow/haskell#172]
Hi all,

I am installing the library on macOS and, after executing stack test inside the downloaded repo I am able to import everything in a ghci session. Nonetheless, when I run ```stack ghci``` outside the tensorflow directory I can't import any tensorflow library. I guess it's because stack is not installing the packages but only loading them on-demand. 

How can I permanently install the tensorflow library so that I can import any module from any ghci session? Sorry if the question does not belong here or if it is too simple.

Thanks.

**Comment by judah** [comment]
Have you tried running `stack install` from inside the downloaded repo?  If that doesn't work, it's probably a mismatch between the LTS version in this repo's `stack.yaml` and your "global project" (`.stack/global-project/stack.yaml) which specifies the LTS version when run outside of a repo (and which `stack` sets up by default).

Solutions are:

- From inside the repo, run `stack install`; then from outside the folder, run `stack ghci --resolver=8.13` to match this repo
- From inside the repo, run `stack install --resolver=YYY` matching whatever's in your global project; then `stack ghci` ought to work.

**Comment by AlejandroCatalina** [comment]
I got it working by copying the stack.yaml inside the tensorflow repo to the outside.

I will try tho the solutions you propose. Thansk!

**Comment by judah** [comment]
Ok, thank you for the follow-up.  Closing since it sounds like there's no issues specific to this repo.
