### ISSUE TITLE
Couldn't match type ‘Int64’ with ‘Int32’

### ISSUE THREAD

**Issue by DanielRodCha** [tensorflow/haskell#186]
Hi,

I've tried to build the repository with stack, but it throws the following error.
Any ideas?

tensorflow-ops-0.1.0.0: build (lib)      
Log files have been written to: /home/username/haskell/.stack-work/logs/
Progress 5/7

--  While building custom Setup.hs for package tensorflow-ops-0.1.0.0 using:
      /home/username/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.2.0 build lib:tensorflow-ops --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/username/haskell/.stack-work/logs/tensorflow-ops-0.1.0.0.log

   Configuring tensorflow-ops-0.1.0.0...
    Preprocessing library tensorflow-ops-0.1.0.0...
    [1 of 7] Compiling TensorFlow.Queue ( src/TensorFlow/Queue.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/TensorFlow/Queue.o )
    [2 of 7] Compiling TensorFlow.Ops   ( src/TensorFlow/Ops.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/TensorFlow/Ops.o )
    
    /home/username/haskell/tensorflow-ops/src/TensorFlow/Ops.hs:380:33: error:
        • Couldn't match type ‘Int64’ with ‘Int32’
          Expected type: Tensor Build Int32
            Actual type: Tensor Build Int64
        • In the first argument of ‘CoreOps.fill’, namely ‘(vector s)’
          In the expression: CoreOps.fill (vector s) (scalar 0)
          In an equation for ‘zeros’:
              zeros (Shape s) = CoreOps.fill (vector s) (scalar 0)

**Comment by fkm3** [comment]
Hi.

In tensorflow 1.7, `fill` accepts both `Int64` and `Int32`. Are you using an older version?

If you need support for an older version of tensorflow, we can probably change the offending code to be backwards compatible by using `Int32` instead.

**Comment by fkm3** [comment]
Closing for now, but let me know if making the code backwards compatible would be useful for you.
