### ISSUE TITLE
"embedding_lookup" appears to be broken, maybe missing some reshaping?

### ISSUE THREAD

**Issue by silky** [tensorflow/haskell#19]
i've been trying to use this function in some model, but i think it's broken. i'm trying to fix it, but i might not have time today, so i want to note it.

there appear to be a few problems:

0. we could add the special-case for np = 1 that is in the original [python](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/embedding_ops.py#L91) (that would actually probably fix the problem i'm facing right now)

1. in [embeddingLookup](https://github.com/tensorflow/haskell/blob/67690d149986f3787d3768594ee544fca6ee1d83/tensorflow-ops/src/TensorFlow/EmbeddingOps.hs#L65) the `dynamicPartition` operation fails for me with:

```
TensorFlowException TF_INVALID_ARGUMENT: "data.shape must start with partitions.shape, got data.shape = [12000], partitions.shape = [100,120,1] ..."
```

i believe this is because we are missing reshaping ids to the ids to get the `flatIds` that is in the python.

2. we're missing a bunch of reshaping at the end

i believe this is just simply missing from the implementation in the haskell code here, compared to the python: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/embedding_ops.py#L160

maybe it's missing because we don't have any of the `framework/tensor_shape.py`  code.

i think to fix this we should probably add some tests. when i get some time i might port some of the python ones again, and hopefully identify some actual problems that way.

**Comment by blackgnezdo** [comment]
Yes, quite possible that it's not entirely faithful. It was used in one project in a particular way. If you could create a breaking unit test it would help a lot :+1:
