### ISSUE TITLE
Support keras

### ISSUE THREAD

**Issue by vincent-hui** [tensorflow/haskell#203]
Does tensorflow-haskell support keras API?

If not, can tensorflow-haskell support keras API and add corresponding examples? Like this
[
Train your first neural network: basic classification](https://github.com/tensorflow/models/blob/master/samples/core/tutorials/keras/basic_classification.ipynb)

Thank a lot

**Comment by blackgnezdo** [comment]
Keras is a much higher level API than what we currently have in tensorflow/haskell. So, no, we don't have anything like it. And yes, it can be built with enough effort though I'm not aware of anybody working in this direction.

I don't think this ticket is actionable as it stands.
