### ISSUE TITLE
building tensorflow-logging with cabal

### ISSUE THREAD

**Issue by theedge456** [tensorflow/haskell#206]
I successfully built tensorflow-0.2.0.0 in a sandbox using cabal on debian.
I would like to build tensorflow-logging but it fails with this error:
Installed split-0.2.3.3
```
CallStack (from HasCallStack):
  die', called at ./Distribution/Client/Install.hs:996:15 in main:Distribution.Client.Install
cabal: Error: some packages failed to install:
snappy-0.2.0.2-2DWlW9b9IiJCqvT6pGXZgw failed during the configure step. The
exception was:
ExitFailure 1
snappy-framing-0.1.2-DUwYyK4LYdPGiK0hizwuxq depends on snappy-framing-0.1.2
which failed to install.

```
Any hint ?

**Comment by blackgnezdo** [comment]
FWIW, I reproduced the following from a clean VM image of Debian 9. My reading is there needs to be some ambient state (like zlib-dev OS package and likely more) to get this whole thing to work. This demonstrates why I prefer using stack for this kind of scenarios. I don't think the issue has to do with with tensorflow-logging and is a case of configuration management which is hard and orthogonal. I'll close the issue.

gnezdo@instance-1:~$ cat /etc/issue
Debian GNU/Linux 9 \n \l
gnezdo@instance-1:~$ sudo apt install cabal-install ghc
gnezdo@instance-1:~$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.1
gnezdo@instance-1:~$ cabal --version
cabal-install version 1.24.0.1
compiled using version 1.24.1.0 of the Cabal library 
nezdo@instance-1:~$ cabal sandbox init
Config file path source is default config file.
Config file /home/gnezdo/.cabal/config not found.
Writing default configuration to /home/gnezdo/.cabal/config
Writing a default package environment file to
/home/gnezdo/cabal.sandbox.config
Creating a new sandbox at /home/gnezdo/.cabal-sandbox
gnezdo@instance-1:~$ cabal update
Downloading the latest package list from hackage.haskell.org
gnezdo@instance-1:~$ cabal install --only-dependencies  tensorflow-logging
Resolving dependencies...
Notice: installing into a sandbox located at /home/gnezdo/.cabal-sandbox
Downloading cereal-0.5.7.0...
Downloading colour-2.3.4...
Configuring cereal-0.5.7.0...
Downloading data-default-class-0.1.2.0...
Configuring data-default-class-0.1.2.0...
Downloading dlist-0.8.0.4...
Downloading fgl-5.6.0.0...
Configuring colour-2.3.4...
Downloading hostname-1.0...
Configuring dlist-0.8.0.4...
Building cereal-0.5.7.0...
Configuring hostname-1.0...
Downloading integer-logarithms-1.0.2.1...
Downloading lens-family-core-1.2.1...
Configuring fgl-5.6.0.0...
Building data-default-class-0.1.2.0...
Configuring integer-logarithms-1.0.2.1...
Building colour-2.3.4...
Downloading lens-labels-0.1.0.2...
Building dlist-0.8.0.4...
Configuring lens-family-core-1.2.1...
Downloading monad-loops-0.4.3...
Downloading mtl-2.2.2...
Downloading network-2.7.0.2...
Downloading old-locale-1.0.0.7...
Downloading primitive-0.6.4.0...
Building hostname-1.0...
Downloading random-1.1...
Downloading semigroups-0.18.5...
Building fgl-5.6.0.0...
Downloading snappy-0.2.0.2...
Downloading split-0.2.3.3...
Building integer-logarithms-1.0.2.1...
Downloading srcloc-0.5.1.2...
Downloading stm-2.4.5.0...
Building lens-family-core-1.2.1...
Downloading text-1.2.3.0...
Downloading transformers-compat-0.6.2...
Downloading unliftio-core-0.1.1.0...
Downloading void-0.7.2...
Downloading zlib-0.6.2...
Installed data-default-class-0.1.2.0
Downloading data-default-instances-containers-0.0.1...
Configuring lens-labels-0.1.0.2...
Configuring monad-loops-0.4.3...
Installed hostname-1.0
Configuring mtl-2.2.2...
Installed dlist-0.8.0.4
Downloading data-default-instances-dlist-0.0.1...
Building lens-labels-0.1.0.2...
Building monad-loops-0.4.3...
Building mtl-2.2.2...
Configuring old-locale-1.0.0.7...
Installed integer-logarithms-1.0.2.1
Configuring network-2.7.0.2...
Installed lens-family-core-1.2.1
Building old-locale-1.0.0.7...
Configuring primitive-0.6.4.0...
Installed lens-labels-0.1.0.2
Building primitive-0.6.4.0...
Configuring random-1.1...
Installed monad-loops-0.4.3
Building random-1.1...
Configuring snappy-0.2.0.2...
Installed old-locale-1.0.0.7
Downloading data-default-instances-old-locale-0.0.1...
Downloading old-time-1.1.0.3...
Configuring srcloc-0.5.1.2...
Failed to install snappy-0.2.0.2
Build log ( /home/gnezdo/.cabal-sandbox/logs/snappy-0.2.0.2.log ):
cabal: Entering directory '/tmp/cabal-tmp-6547/snappy-0.2.0.2'
Configuring snappy-0.2.0.2...
cabal: Missing dependencies on foreign libraries:
* Missing C libraries: snappy, stdc++
This problem can usually be solved by installing the system packages that
provide these libraries (you may need the "-dev" versions). If the libraries
are already installed but in a non-standard location then you can use the
flags --extra-include-dirs= and --extra-lib-dirs= to specify where they are.
cabal: Leaving directory '/tmp/cabal-tmp-6547/snappy-0.2.0.2'
Building srcloc-0.5.1.2...
Configuring stm-2.4.5.0...
Installed mtl-2.2.2
Downloading lens-family-1.2.1...
Configuring split-0.2.3.3...
Installed colour-2.3.4
Downloading ansi-terminal-0.8.0.4...
Building stm-2.4.5.0...
Building split-0.2.3.3...
Building network-2.7.0.2...
Configuring semigroups-0.18.5...
Installed split-0.2.3.3
Configuring unliftio-core-0.1.1.0...
Installed srcloc-0.5.1.2
Building semigroups-0.18.5...
Configuring transformers-compat-0.6.2...
Installed random-1.1
Building unliftio-core-0.1.1.0...
Configuring text-1.2.3.0...
Installed stm-2.4.5.0
Downloading stm-chans-3.0.0.4...
Building transformers-compat-0.6.2...
Building text-1.2.3.0...
Configuring void-0.7.2...
Installed semigroups-0.18.5
Configuring zlib-0.6.2...
Installed unliftio-core-0.1.1.0
Building void-0.7.2...
Failed to install zlib-0.6.2
Build log ( /home/gnezdo/.cabal-sandbox/logs/zlib-0.6.2.log ):
cabal: Entering directory '/tmp/cabal-tmp-6553/zlib-0.6.2'
Configuring zlib-0.6.2...
cabal: Missing dependency on a foreign library:
* Missing (or bad) header file: zlib.h
* Missing C library: z
This problem can usually be solved by installing the system package that
provides this library (you may need the "-dev" version). If the library is
already installed but in a non-standard location then you can use the flags
--extra-include-dirs= and --extra-lib-dirs= to specify where it is.
If the header file does exist, it may contain errors that are caught by the C
compiler at the preprocessing stage. In this case you can re-run configure
with the verbosity flag -v3 to see the error messages.
cabal: Leaving directory '/tmp/cabal-tmp-6553/zlib-0.6.2'
Configuring data-default-instances-containers-0.0.1...
Configuring data-default-instances-dlist-0.0.1...
Installed void-0.7.2
Building data-default-instances-containers-0.0.1...
Building data-default-instances-dlist-0.0.1...
Configuring old-time-1.1.0.3...
Installed fgl-5.6.0.0
Configuring ansi-terminal-0.8.0.4...
Installed data-default-instances-containers-0.0.1
Configuring lens-family-1.2.1...
Installed data-default-instances-dlist-0.0.1
Building ansi-terminal-0.8.0.4...
Configuring data-default-instances-old-locale-0.0.1...
Installed cereal-0.5.7.0
Building lens-family-1.2.1...
Configuring stm-chans-3.0.0.4...
Installed transformers-compat-0.6.2
Downloading exceptions-0.10.0...
Building data-default-instances-old-locale-0.0.1...
Installed data-default-instances-old-locale-0.0.1
Downloading data-default-0.7.1.1...
Configuring exceptions-0.10.0...
Building old-time-1.1.0.3...
Configuring data-default-0.7.1.1...
Installed lens-family-1.2.1
Building exceptions-0.10.0...
Building data-default-0.7.1.1...
Installed primitive-0.6.4.0
Downloading vector-0.12.0.1...
Configuring vector-0.12.0.1...
Installed data-default-0.7.1.1
Building vector-0.12.0.1...
Installed ansi-terminal-0.8.0.4
Downloading ansi-wl-pprint-0.6.8.2...
Configuring ansi-wl-pprint-0.6.8.2...
Building stm-chans-3.0.0.4...
Installed network-2.7.0.2
Building ansi-wl-pprint-0.6.8.2...
Installed exceptions-0.10.0
Downloading resourcet-1.2.1...
Downloading temporary-1.3...
Configuring resourcet-1.2.1...
Configuring temporary-1.3...
Building temporary-1.3...
Building resourcet-1.2.1...
Installed stm-chans-3.0.0.4
Installed old-time-1.1.0.3
Installed ansi-wl-pprint-0.6.8.2
Downloading optparse-applicative-0.14.2.0...
Configuring optparse-applicative-0.14.2.0...
Installed temporary-1.3
Building optparse-applicative-0.14.2.0...
Installed resourcet-1.2.1
Installed optparse-applicative-0.14.2.0
Installed text-1.2.3.0
Downloading hashable-1.2.7.0...
Downloading mainland-pretty-0.7...
Downloading parsec-3.1.13.0...
Configuring hashable-1.2.7.0...
Configuring mainland-pretty-0.7...
Downloading polyparse-1.12...
Configuring polyparse-1.12...
Configuring parsec-3.1.13.0...
Building hashable-1.2.7.0...
Building mainland-pretty-0.7...
Building parsec-3.1.13.0...
Building polyparse-1.12...
Installed hashable-1.2.7.0
Downloading async-2.2.1...
Downloading scientific-0.3.6.2...
Downloading unordered-containers-0.2.9.0...
Configuring async-2.2.1...
Configuring scientific-0.3.6.2...
Configuring unordered-containers-0.2.9.0...
Building async-2.2.1...
Building scientific-0.3.6.2...
Building unordered-containers-0.2.9.0...
Installed mainland-pretty-0.7
Installed async-2.2.1
Downloading typed-process-0.2.3.0...
Downloading unliftio-0.2.7.0...
Configuring typed-process-0.2.3.0...
Configuring unliftio-0.2.7.0...
Building typed-process-0.2.3.0...
Building unliftio-0.2.7.0...
Installed parsec-3.1.13.0
Installed scientific-0.3.6.2
Downloading attoparsec-0.13.2.2...
Configuring attoparsec-0.13.2.2...
Installed typed-process-0.2.3.0
Building attoparsec-0.13.2.2...
Installed polyparse-1.12
Downloading cpphs-1.20.8...
Configuring cpphs-1.20.8...
Building cpphs-1.20.8...
Installed unliftio-0.2.7.0
Installed unordered-containers-0.2.9.0
Installed cpphs-1.20.8
Downloading haskell-src-exts-1.19.1...
Configuring haskell-src-exts-1.19.1...
Failed to install haskell-src-exts-1.19.1
Build log ( /home/gnezdo/.cabal-sandbox/logs/haskell-src-exts-1.19.1.log ):
cabal: Entering directory '/tmp/cabal-tmp-6530/haskell-src-exts-1.19.1'
Configuring haskell-src-exts-1.19.1...
cabal: The program 'happy' version >=1.19 is required but it could not be
found.
cabal: Leaving directory '/tmp/cabal-tmp-6530/haskell-src-exts-1.19.1'
Installed vector-0.12.0.1
Downloading vector-algorithms-0.7.0.1...
Configuring vector-algorithms-0.7.0.1...
Building vector-algorithms-0.7.0.1...
Installed attoparsec-0.13.2.2
Downloading proto-lens-0.2.2.0...
Configuring proto-lens-0.2.2.0...
Building proto-lens-0.2.2.0...
Installed proto-lens-0.2.2.0
Downloading proto-lens-descriptors-0.2.2.0...
Configuring proto-lens-descriptors-0.2.2.0...
Building proto-lens-descriptors-0.2.2.0...
Installed vector-algorithms-0.7.0.1
Downloading mono-traversable-1.0.9.0...
Configuring mono-traversable-1.0.9.0...
Building mono-traversable-1.0.9.0...
Installed proto-lens-descriptors-0.2.2.0
Installed mono-traversable-1.0.9.0
Downloading conduit-1.3.0.3...
Configuring conduit-1.3.0.3...
Building conduit-1.3.0.3...
Installed conduit-1.3.0.3
Downloading cereal-conduit-0.8.0...
Configuring cereal-conduit-0.8.0...
Building cereal-conduit-0.8.0...
Installed cereal-conduit-0.8.0
cabal: Error: some packages failed to install:
conduit-extra-1.3.0 depends on zlib-0.6.2 which failed to install.
haskell-src-exts-1.19.1 failed during the configure step. The exception was:
ExitFailure 1
proto-lens-protobuf-types-0.2.2.0 depends on haskell-src-exts-1.19.1 which
failed to install.
proto-lens-protoc-0.2.2.3 depends on haskell-src-exts-1.19.1 which failed to
install.
snappy-0.2.0.2 failed during the configure step. The exception was:
ExitFailure 1
snappy-framing-0.1.2 depends on snappy-0.2.0.2 which failed to install.
stm-conduit-4.0.0 depends on zlib-0.6.2 which failed to install.
streaming-commons-0.2.1.0 depends on zlib-0.6.2 which failed to install.
tensorflow-0.2.0.0 depends on haskell-src-exts-1.19.1 which failed to install.
tensorflow-core-ops-0.2.0.0 depends on haskell-src-exts-1.19.1 which failed to
install.
tensorflow-opgen-0.2.0.0 depends on haskell-src-exts-1.19.1 which failed to
install.
tensorflow-ops-0.2.0.0 depends on haskell-src-exts-1.19.1 which failed to
install.
tensorflow-proto-0.2.0.0 depends on haskell-src-exts-1.19.1 which failed to
install.
tensorflow-records-0.1.0.0 depends on snappy-0.2.0.2 which failed to install.
tensorflow-records-conduit-0.1.0.0 depends on snappy-0.2.0.2 which failed to
install.
zlib-0.6.2 failed during the configure step. The exception was:
ExitFailure 1
gnezdo@instance-1:~$
