### ISSUE TITLE
Support tensorflow 1.10 ?

### ISSUE THREAD

**Issue by jyp** [tensorflow/haskell#210]
I tried to compile the package on the basis of nixos master branch, and got:
```
parseAttrType: unrecognized type "func" for op "BatchFunction"
CallStack (from HasCallStack):
  error, called at src/TensorFlow/OpGen/ParsedOp.hs:342:10 in tensorflow-opgen-0.2.0.0-1UpNHobsfgjGI7NFMU58sK:TensorFlow.OpGen.ParsedOp
```
I am suspecting that this is due to tensorflow haskell not supporting tensorflow 1.10.
Is this a correct assessment? If so, any plans to support version 1.10?

**Comment by blackgnezdo** [comment]
@jyp, please take a look at the [commit for 1.9 upgrade](https://github.com/tensorflow/haskell/commit/ecfea97992c0a8dd0f2385e96658fef7e5ca23bf). The failing function in question should probably be blacklisted.

**Comment by jyp** [comment]
@blackgnezdo I can't make sense of your message. I am talking about supporting 1.10, I don't see anything related to that in the commit for 1.9. I don't know what "the function in question is" and I don't know what blacklisting means. The commit does not seem to give any hint regarding that.

**Comment by blackgnezdo** [comment]
If you make a commit similar to the one I pointed at you can upgrade us to 1.10. There's a change to Setup.hs where the blackList variable is extended. You will need to add "BatchFunction" to that list.

Is this helpful?

**Comment by jyp** [comment]
@blackgnezdo Thanks, that is clear. I will probably not work on this in the short term though.

**Comment by teto** [comment]
This patch 
```
diff --git b/Setup.hs a/Setup.hs
index 9a5b036..9749de8 100644
--- b/Setup.hs
+++ a/Setup.hs
@@ -91,6 +91,8 @@ fudgePackageDesc lbi p = p
 blackList =
     [ -- Requires the "func" type:
       "FilterDataset"
+    , "BatchFunction"
+    , "StatefulPartitionedCall"
     , "FlatMapDataset"
     , "For"
     , "GeneratorDataset"

```
with this overlay
```

  haskell = prev.haskell // {
    packageOverrides = hself: hprev: rec {  

      zeromq4-haskell = prev.haskell.lib.dontCheck hprev.zeromq4-haskell;

      tensorflow-core-ops = prev.haskell.lib.appendPatch (hprev.tensorflow-core-ops) ../../tensorflow.patch;
    };
  };

```
seems to do it.

**Comment by teto** [comment]
(related https://github.com/tensorflow/haskell/issues/215)

**Comment by cdepillabout** [comment]
tensorflow haskell has recently been updated to support TensorFlow 1.14, so this issue can probably be closed:

https://github.com/tensorflow/haskell/pull/244
