### ISSUE TITLE
Is Where3 bound?

### ISSUE THREAD

**Issue by jyp** [tensorflow/haskell#211]
Is Where3 [1] available? If not, what would it take to make it so?
Is there another function which would do an equivalent operation?

[1] https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/where3

**Comment by fkm3** [comment]
I think you want `select`: https://tensorflow.github.io/haskell/haddock/tensorflow-core-ops-0.2.0.0/TensorFlow-GenOps-Core.html#v:select
"Select" is the name of the underlying op for python's `tf.where` and probably also for C++'s `Where3`.

**Comment by jyp** [comment]
Thanks @fkm3!

How would I trace in general the name bound by tensorflow haskell to its documentation? That is, I can click "source" to see that select binds "Select", but which API is that? I thought so far it was the C++ api, but apparently this does not work in this case. I see that there is a C api too, but I can't find its documentation.
