### ISSUE TITLE
Publish tensorflow-mnist-input-data to Hackage

### ISSUE THREAD

**Issue by basvandijk** [tensorflow/haskell#215]
`tensorflow-mnist` is [published on Hackage](http://hackage.haskell.org/package/tensorflow-mnist). However its dependency `tensorflow-mnist-input-data` [isn't](http://hackage.haskell.org/package/tensorflow-mnist-input-data). This causes problems when installing the package or [packaging it for NixOS](https://github.com/NixOS/nixpkgs/pull/46103#issuecomment-418980239).

**Comment by blackgnezdo** [comment]
Try as I might I as unable to determine the licensing terms for the data set. Thus I resorted to downloading it locally when people want to run the examples. Is NixOS capable of grabbing the files from the original source [as we do](https://github.com/tensorflow/haskell/blob/master/tensorflow-mnist-input-data/Setup.hs)?

**Comment by basvandijk** [comment]
Yes NixOS is capable of downloading the files. I now [do that here](https://github.com/NixOS/nixpkgs/blob/1fc5a6d2b6bf3acfd5e4761fd2cb0c549c6045f0/pkgs/development/haskell-modules/configuration-tensorflow.nix#L69).

**Comment by fkm3** [comment]
FYI: I didn't mean to publish tensorflow-mnist to hackage. It isn't a library, so I'm not sure it is useful to have on hackage and, similarly, you probably don't want it in nixpkgs.
