### ISSUE TITLE
Saving and Restoring the Session State (to Haskell)

### ISSUE THREAD

**Issue by schnecki** [tensorflow/haskell#228]
Hi,

I was wondering whether it is possible to read the current session state, close the session, later open a new one and reload the former session state to be able to continue the calculations.

This would prevent of encapsulating the whole program into `SessionT`. I found the possibility of saving `Tensor`s, which however might not be the full state. 

Furthermore, I tried using `readerSerializeStateV2` and `readerRestoreState` but couldn't get anything running, nor I'm sure that these functions do what I'd like to do.

Has anyone done something like this yet and if so, is there a code example somewhere? Or might this not be possible at all yet?

**Comment by rikvdkleij** [comment]
I have tried to find a solution based on https://github.com/tensorflow/haskell/blob/61e58fd33f50fdd70a34489a6d599118575d2068/tensorflow-mnist/tests/ParseTest.hs  which only contains the restoring part.

The problem is the saving part. It looks like applying `asGraphDef` on the node which contains the graph that it does not serializes everything because when I load the graph in the next session and then restore the model parameters (which have the same name as in the training) TF gives an error : 
`*** Exception: TensorFlowException TF_INVALID_ARGUMENT "Node 'Assign_7': Unknown input node 'b'"`
(`b` is name of model parameter)

A part of the code which is relevant for saving the graph:
```
import qualified TensorFlow.Variable as V

    w <- V.zeroInitializedVariable' (TF.opName .~ "w") (TF.Shape [])
    b <- V.zeroInitializedVariable' (TF.opName .~ "b") (TF.Shape [])
    inputs :: TF.Tensor TF.Value Float <- TF.build $  TF.placeholder'(TF.opName .~ "x")  [-1, fromIntegral (length xData)]
    let yHat = (inputs `TF.mul` V.readValue w) `TF.add` V.readValue b

    let graph = TF.asGraphDef $ TF.render yHat
    let graphMessage = encodeMessage graph
    liftIO $ BS.writeFile "graph.pb" graphMessage
```

Later on the trained model parameters (`w_v` and `b_v` are the values) are stored  because TF `Variable` can not be used for that.
```
  TF.runSession $ do
    w1 <- TF.initializedVariable' (TF.opName .~ "w") (TF.scalar w_v)
    w2 <- TF.initializedVariable' (TF.opName .~ "b") (TF.scalar b_v)
    let path = B8.pack "checkpoint.chkpt"
    TF.save path [w1, w2] >>= TF.run_
```

Also when I print the graph I do not see the node definitions of the model parameters. The graph only refers to.it For example for `w`:
`_NodeDef'input = ["w"],`

Any help is really appreciated because I do not know how to continue.

**Comment by schnecki** [comment]
Hi,
I as well tried to use `asGraphDef` and `addGraphDef` but could not find a solution yet. Furthermore, I tried to save the model to a file in the system's temporary folder (`/tmp` for linux) which is usually kept in RAM and thus would be an acceptable approach. This would work with `save` and `restore` from `TensorFlow.Ops`. 

After researching, as I would like to save and restore the full model, inclusive current state of the training I guess a `MetaGraph` would be the correct thing. However, even though `MetaGraphDef` [1] seems to be implemented, I do not know how to save and restore these. I could not find an example in the test folders, nor on the internet. Any ideas?

Anyways, so my approach was to try it out with the former methods, but I did not succeed in that either. I uploaded a small test project as a zip (change the `stack.yaml` file to your needs): https://files.fm/u/c7p4ykkm. I am using a feedforward neural network model (for now let's forget about training). The interesting part of `app/Main.hs` file is as follows: 

    main = do 
      let path = B8.pack $ tempDir ++ "/model"
          graphDef = TF.asGraphDef modelBuilder
          outputTensor = head (graphDef ^. TF.node)
          outputTensorName = outputTensor ^. TF.name
          inputTensorName = last (graphDef ^. TF.node) ^. TF.name
          namesPredictor = graphDef ^.. TF.node . traversed . TF.name
      putStrLn $ "outputTensorName: " ++ show outputTensorName
      print namesPredictor
      let outRef, inRef :: TF.Tensor TF.Ref Float
          outRef = TF.tensorFromName outputTensorName
          inRef = TF.tensorFromName inputTensorName
          inp = encodeImageBatch [[0.7 :: Float, 0.4]]
      -- SESSION 1
      TF.runSession $
        -- TF.addGraphDef graphDef -- *** Exception: TensorFlowException TF_INVALID_ARGUMENT "Node 'Mean_35' is not unique"
       do
        model <- TF.build modelBuilder
        bef <- head . V.toList <$> TF.runWithFeeds [TF.feed inRef inp] outRef
        liftIO $ print bef
        TF.save path [inRef, outRef] >>= TF.runWithFeeds_ [TF.feed inRef inp]
      -- SESSION 2
      TF.runSession $
        -- TF.addGraphDef graphDef  -- *** Exception: TensorFlowException TF_INVALID_ARGUMENT "Node 'Mean_35' is not unique"
       do
        model <- TF.build modelBuilder
        -- next line: *** Exception: TensorFlowException TF_INVALID_ARGUMENT "Input 0 of node Assign_39 was passed float from Mean_35:0 incompatible with expected float_ref."
        -- TF.restore path outRef >>= TF.runWithFeeds_ [TF.feed inRef inp]
        let xData = [[0.7 :: Float, 0.4]]
        let inp = encodeImageBatch xData
            labels = encodeLabelBatch yData
        bef <- head . V.toList <$> TF.runWithFeeds [TF.feed inRef inp] outRef
        liftIO $ print bef
    
      -- GOAL: The aim is to preserve the model through multiple sessions, in which each the model may be trained.

When I use `TF.addGraphDef graphDef` tensorflow seems to render the graph twice and thus multiple instances of the graph exists which lead to non-unique names, while when I use `TF.save` and `TF.restore` I get a type missmatch, but restoring requires a `Ref`. The same error occurs if I feed into `inputLayer Ref` (Type: `TF.Tensor TF.Value Float`) as opposed to `inRef` (Type: `TF.Tensor TF.Ref Float`). 

The exact `exception` messages are given in the code listing above. Does anyone have an idea why these exception are happening or how I might be able to prevent them? 




P.S.: I found https://github.com/tensorflow/haskell/blob/8e1d85b5e5bd56d54ff6d463c8581c57ab5526d9/tensorflow-ops/tests/OpsTest.hs which implements `testSaveRestore` for a single variable tensor, which seems to work. But in my example, I cannot scale that to the neural network.
[1] https://tensorflow.github.io/haskell/haddock/tensorflow-proto-0.2.0.0/Proto-Tensorflow-Core-Protobuf-MetaGraph.html#v:MetaGraphDef

**Comment by schnecki** [comment]
> Also when I print the graph I do not see the node definitions of the model parameters. The graph only refers to.it For example for `w`:
> `_NodeDef'input = ["w"],`
> 
> Any help is really appreciated because I do not know how to continue.

I get `Attempting to use uninitialized value Variable_*` whenever I try to use a model loaded by `TF.addGraphDef` which was not built inside of `TF.runSession`. So for instance if I change the code of `SESSION 1` from above to:

    -- SESSION 1
    TF.runSession $ do
      TF.addGraphDef graphDef -- *** Exception: TensorFlowException TF_INVALID_ARGUMENT "Node 'Mean_35' is not unique"
      -- model <- TF.build modelBuilder
      bef <- head . V.toList <$> TF.runWithFeeds [TF.feed inRef inp] outRef
      liftIO $ print bef
      TF.save path [inRef, outRef] >>= TF.runWithFeeds_ [TF.feed inRef inp]

I do have an uninitialized variable exception, which I think is what you have as well. The exact error message is `*** Exception: TensorFlowException TF_FAILED_PRECONDITION "Attempting to use uninitialized value Variable_3\n\t [[Node: MatMul_25 = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](_arg_Placeholder_0_0_0, Variable_3)]]"`

Surely, if I use `TF.build` and `TF.addGraphDef`, I get the non-uniqueness exception, as refered to above. If I use `TF.build` only in every `Session` TensorFlow builds a new Graph and the previous data is lost between sessions.

**Comment by blackgnezdo** [comment]
The internal application I built on top of this library stopped at the point of evaluating the model quality. I never really exported the model.

I think you are in the best position to figure things out (because you have the itch to scratch). I am really busy at work at the moment, so not likely to be of much use.

**Comment by rikvdkleij** [comment]
@schnecki Did you continue to find a solution?

**Comment by rikvdkleij** [comment]
> I think you are in the best position to figure things out (because you have the itch to scratch). I am really busy at work at the moment, so not likely to be of much use.

I have no idea how to continue so maybe you can point us in the right direction? 
How to serialize the network graph in way that deserializing it accepts the model parameter values from the checkpoint.

**Comment by schnecki** [comment]
@rikvdkleij yes I did figure out how to save and restore the graph using the `TF.save` and `TF.restore` functions. However saving and restoring the minimizer part requires a different implementation of `TF.minimizeWith` as these only work over `TF.Variable`s, whereas I need `TF.Ref`s for the saving and restoring. However note the todo-text in `Variable.hs`: 

> TODO: given that distinction, figure out a good story around gradients and save/restore.  Then, merge this module into TensorFlow.Ops.

So I guess this issue just exists as the module is either not fully implemented, or merged yet. So I decided to use `TF.Ref`s for model building. Furthermore, for saving/restoring I need to run the model using `TF.run_` for the neural network subgraph and `TF.runWithFeeds` for the training model subgraph. The problem is that the later one the changes the tensor values, while the former one does not request an input for the input layer placeholder. I don't know why the former one runs without any input (`TF.save pathModel (neuralNetworkVariables model) >>= TF.run_`), nor how to prevent changes to the tensors. Thus the order of saving and restoring of the model is important. 

Below is the code I came up with, plus you find the additional `TF.minimizeWithRefs` function at this commit of my fork: https://github.com/schnecki/haskell/commit/3cd2e15e58e74b6a5de2bbf822a9650a741115c6. Btw, I hadn't have time to clean it up nicely, but wanted to respond quickly. Sorry for that.

Main imports

    import qualified Proto.Tensorflow.Core.Framework.Graph_Fields   as TF (node)
    import qualified Proto.Tensorflow.Core.Framework.NodeDef_Fields as TF (name, op, value)
    import qualified TensorFlow.Build                               as TF (addNewOp,
                                                                           evalBuildT,
                                                                           explicitName, opDef,
                                                                           opDefWithName,
                                                                           opType, runBuildT,
                                                                           summaries)
    import qualified TensorFlow.Core                                as TF hiding (value)
    import qualified TensorFlow.GenOps.Core                         as TF (abs, add,
                                                                           approximateEqual,
                                                                           approximateEqual,
                                                                           assign, cast,
                                                                           getSessionHandle,
                                                                           getSessionTensor,
                                                                           identity',
                                                                           lessEqual,
                                                                           lessEqual, matMul,
                                                                           mul,
                                                                           readerSerializeState,
                                                                           relu, shape, square,
                                                                           sub,
                                                                           truncatedNormal)
    import qualified TensorFlow.Minimize                            as TF
    import qualified TensorFlow.Ops                                 as TF (initializedVariable,
                                                                           initializedVariable',
                                                                           placeholder,
                                                                           placeholder',
                                                                           reduceMean,
                                                                           reduceSum, restore,
                                                                           save, scalar,
                                                                           vector,
                                                                           zeroInitializedVariable,
                                                                           zeroInitializedVariable')
    import qualified TensorFlow.Tensor                              as TF (Ref (..),
                                                                           collectAllSummaries,
                                                                           tensorNodeName,
                                                                           tensorRefFromName,
                                                                           tensorValueFromName)

Model Building:

    data Model = Model
      { inputLayerName         :: Text -- ^ Input layer name for feeding input.
      , outputLayerName        :: Text -- ^ Output layer name for predictions.
      , labelLayerName         :: Text -- ^ Labels input layer name for training.
      , errorRateName          :: Text -- ^ Error rate tensor name.
      , trainingNode           :: TF.ControlNode -- ^ Training node.
      , neuralNetworkVariables :: [TF.Tensor TF.Ref Float] -- ^ Neural network variables for saving and restoring.
      , trainingVariables      :: [TF.Tensor TF.Ref Float] -- ^ Training data/settings for saving and restoring.
      }
    
    modelBuilder :: (TF.MonadBuild m) => m Model
    modelBuilder = do
    
      -- Input layer.
      let inpLayerName = "input"
      input <- TF.placeholder' (TF.opName .~ TF.explicitName inpLayerName) (fromList [batchSize, numInputs])  -- Input layer.
      -- Hidden layer.
      let numUnits = 2
      hiddenWeights <- TF.initializedVariable' (TF.opName .~ "w1") =<< randomParam numInputs [numInputs, numUnits]
      hiddenBiases <- TF.zeroInitializedVariable' (TF.opName .~ "b1") [numUnits]
      let hiddenZ = (input `TF.matMul` hiddenWeights) `TF.add` hiddenBiases
      let hidden = TF.relu hiddenZ
      -- Logits
      outputWeights <- TF.initializedVariable' (TF.opName .~ "w2") =<< randomParam numInputs [numUnits, 1]
      outputBiases <- TF.zeroInitializedVariable' (TF.opName .~ "b2") [1]
      let outputs = (hidden `TF.matMul` outputWeights) `TF.add` outputBiases
      -- Output
      let outLayerName = "output"
      predictor <- TF.render $ TF.identity' (TF.opName .~ TF.explicitName outLayerName) $ TF.reduceMean $ TF.relu outputs
    
      -- Data Collection
      let weights = [hiddenWeights, hiddenBiases, outputWeights, outputBiases] :: [TF.Tensor TF.Ref Float]
    
      -- Create training action. 
      -- THE REST NEEDS A DIFFERENT IMPLEMENTATION OF TF.minimizeWith HERE CALLED TF.minimizeWithRefs
      let labLayerName = "labels"
      -- labels <- TF.placeholder' (TF.opName .~ TF.explicitName labLayerName) [batchSize]
      -- let loss = TF.reduceSum $ TF.square (outputs `TF.sub` labels)
      --     adamConfig = TF.AdamConfig { TF.adamLearningRate = 0.01 , TF.adamBeta1 = 0.9 , TF.adamBeta2 = 0.999 , TF.adamEpsilon = 1e-8 }
      -- (trainStep, trainVars) <- TF.minimizeWithRefs (TF.adamRefs' adamConfig) loss weights (map TF.Shape [[numInputs, numUnits], [numUnits], [numUnits,1],[1]])
      --  
      -- let correctPredictions = TF.abs (predictor `TF.sub` labels) `TF.lessEqual` TF.scalar 0.01
      let errRateName = "error"
      -- (_ :: TF.Tensor TF.Value Float) <- TF.render $ TF.identity' (TF.opName .~ TF.explicitName errRateName) $ 1 - TF.reduceMean (TF.cast correctPredictions)
    
      return Model
        { inputLayerName = inpLayerName
        , outputLayerName = outLayerName
        , labelLayerName = labLayerName
        , errorRateName = errRateName
        , trainingNode = trainStep
        , neuralNetworkVariables = weights
        , trainingVariables = trainVars
        }

Saving/Restoring

    let encodeImageBatch xs = TF.encodeTensorData [genericLength xs, 2] (V.fromList $ mconcat xs)
        encodeLabelBatch xs = TF.encodeTensorData [genericLength xs] (V.fromList xs)
  
    tempDir <- getCanonicalTemporaryDirectory >>= flip createTempDirectory ""
    print $ "TempDir: " ++ tempDir
    let pathModel = B8.pack $ tempDir ++ "/model"
        pathTrain = B8.pack $ tempDir ++ "/train"
  
    let graphDef = TF.asGraphDef modelBuilder
        namesPredictor = graphDef ^.. TF.node.traversed.TF.name
  
    let outputTensor = head (graphDef ^. TF.node)
        outputTensorName = outputTensor ^. TF.name
        inputTensorName = last (graphDef ^. TF.node)^. TF.name
  
    let inp = encodeImageBatch [[0.7 :: Float,0.4]]
        lab = encodeLabelBatch [2.3 :: Float]
    -- SESSION 1
    TF.runSession $ do
      model <- modelBuilder
      let inRef = TF.tensorFromName (inputLayerName model) :: TF.Tensor TF.Ref Float
          outRef = TF.tensorFromName (outputLayerName model) :: TF.Tensor TF.Ref Float
          labRef = TF.tensorFromName (labelLayerName model) :: TF.Tensor TF.Ref Float
  
      bef <- head . V.toList <$> TF.runWithFeeds [TF.feed inRef inp] outRef
      liftIO $ putStrLn $ "START SESS 1: " ++ show bef
  
      forM_ ([0..1000] :: [Int]) $ \i -> do
        (x1Data :: [Float]) <- liftIO $ replicateM 1 randomIO
        (x2Data :: [Float]) <- liftIO $ replicateM 1 randomIO
        let xData = [[x1,x2] | x1 <- x1Data, x2 <- x2Data ]
        let yData = map (\(x1:x2:_) -> x1 * 0.3 + x2 * 0.5) xData
        let inpTrain = encodeImageBatch xData
            labTrain = encodeLabelBatch yData
        TF.runWithFeeds_ [TF.feed inRef inpTrain, TF.feed labRef labTrain] (trainingNode model)
  
        when (i `mod` 100 == 0) $ do
          bef <- head . V.toList <$> TF.runWithFeeds [TF.feed inRef inp] outRef
          liftIO $ putStrLn $ "Value: " ++ show bef
          varVals :: [V.Vector Float] <- TF.run (neuralNetworkVariables model)
          liftIO $ putStrLn $ "Weights: " ++ show (V.toList <$> varVals)
  
      aft <- head . V.toList <$> TF.runWithFeeds [TF.feed inRef inp] outRef
      liftIO $ putStrLn $ "END SESS 1: " ++ show aft
      TF.save pathModel (neuralNetworkVariables model) >>= TF.run_
      varVals :: [V.Vector Float] <- TF.runWithFeeds [TF.feed inRef inp, TF.feed labRef lab] (neuralNetworkVariables model)
      liftIO $ putStrLn $ "SESS 1 Weights: " ++ show (V.toList <$> varVals)
      TF.save pathTrain (trainingVariables model) >>= TF.runWithFeeds_ [TF.feed inRef inp, TF.feed labRef lab]
  
    -- SESSION 2
    TF.runSession $ do
      model <- modelBuilder
      let inRef = TF.tensorFromName (inputLayerName model) :: TF.Tensor TF.Ref Float
          outRef = TF.tensorFromName (outputLayerName model) :: TF.Tensor TF.Ref Float
          labRef = TF.tensorFromName (labelLayerName model) :: TF.Tensor TF.Ref Float
  
      -- Restore training config and weights afterwards as the first operations learns/modifies weights
      mapM (TF.restore pathTrain) (trainingVariables model) >>= TF.runWithFeeds_ [TF.feed inRef inp, TF.feed labRef lab]
      mapM (TF.restore pathModel) (neuralNetworkVariables model) >>= TF.run_
      varVals :: [V.Vector Float] <- TF.run (neuralNetworkVariables model)
      liftIO $ putStrLn $ "SESS 2 Weights: " ++ show (V.toList <$> varVals)
      bef <- head . V.toList <$> TF.runWithFeeds [TF.feed inRef inp] outRef
      liftIO $ putStrLn $ "START SESS 2: " ++ show  bef
  
      forM_ ([0..1000] :: [Int]) $ \i -> do
        (x1Data :: [Float]) <- liftIO $ replicateM 1 randomIO
        (x2Data :: [Float]) <- liftIO $ replicateM 1 randomIO
        let xData = [[x1,x2] | x1 <- x1Data, x2 <- x2Data ]
        let yData = map (\(x1:x2:_) -> x1 * 0.3 + x2 * 0.5) xData
        let inpTrain = encodeImageBatch xData
            labTrain = encodeLabelBatch yData
        TF.runWithFeeds_ [TF.feed inRef inpTrain, TF.feed labRef labTrain] (trainingNode model)
  
        when (i `mod` 100 == 0) $ do
          bef <- head . V.toList <$> TF.runWithFeeds [TF.feed inRef inp] outRef
          liftIO $ putStrLn $ "Value: " ++ show bef
          varVals :: [V.Vector Float] <- TF.run (neuralNetworkVariables model)
          liftIO $ putStrLn $ "Weights: " ++ show (V.toList <$> varVals)
          -- varVals :: [V.Vector Float] <- TF.runWithFeeds [TF.feed inRef inp, TF.feed labRef lab] (trainingVariables model)
          -- liftIO $ putStrLn $ "Train Vars: " ++ show (V.toList <$> varVals)
  
      aft <- head . V.toList <$> TF.runWithFeeds [TF.feed inRef inp] outRef
      liftIO $ putStrLn $ "END SESS 2: " ++ show  aft

**Comment by schnecki** [comment]
Hope this helps. I could not get `asGraphDef` and `GraphToDef` to work. 
Btw I think [1] is the correct (Python) documentation for the `save` and `restore` functions implemented in Haskell.

[1] https://www.tensorflow.org/guide/saved_model#save_and_restore_models

**Comment by rikvdkleij** [comment]
@schnecki Thanks for your reply!

> Hope this helps. I could not get asGraphDef and GraphToDef to work.

Does your your solution work? Also with respect to that `Variable` has to be used for `minimizeWith` and `Tensor Ref` has to be used for saving and restoring the trained model parameters.

I got stuck when I wanted to created generic Minimizer for `Tensor Ref`.

**Comment by schnecki** [comment]
> Does your your solution work? Also with respect to that `Variable` has to be used for `minimizeWith` and `Tensor Ref` has to be used for saving and restoring the trained model parameters.
> 
> I got stuck when I wanted to created generic Minimizer for `Tensor Ref`.

Yes, that's what I did in the commit linked above. Here is the full file, the most interesting part is the `adamRefs'` function at the bottom of the file: https://github.com/schnecki/haskell/blob/3cd2e15e58e74b6a5de2bbf822a9650a741115c6/tensorflow-ops/src/TensorFlow/Minimize.hs#L162. This function also returns the variable `Ref`s created, s.t. these can be stored as well.

Note that `MinimizeWithRefs` is defined as 

    type MinimizerRefs a =
        forall m. TF.MonadBuild m =>
         [TF.Tensor TF.Ref a] -> [TF.Shape] -> [TF.Tensor TF.Value a] -> 
         m (TF.ControlNode, [TF.Tensor TF.Ref a])

That is, it requires the shapes as input parameter. I did not succeed in reading the `Shape` values from the parameter input list yet, and I believe it is not possible inside of the Build-Monad. However, that information is known while building the model anyways. Further one could provide functions for building and connecting layers which keep track of the shapes internally (possibly using a `Writer` or `State` Monad) and provides these at the point of building the training subgraph. 

Here is some example output:

    "TempDir: /tmp/-8edf803269ae9ad9"
    2019-01-22 15:20:42.017194: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
    START SESS 1: 0.0
    Value: 0.0
    Weights: [[1.2618805,-0.5616363,-0.93943864,1.3911341],[0.0,-7.441336e-3],[-0.7657423,-0.3099296],[7.441341e-3]]
    Value: 0.42756575
    Weights: [[0.9918887,-0.7941813,-1.1305867,1.1296624],[-0.26752135,-0.277374],[-0.47679025,-4.4168636e-2],[0.42756575]]
    Value: 0.4573116
    Weights: [[0.95208585,-0.8065466,-1.143565,1.1155546],[-0.2913579,-0.28733322],[-0.41328138,2.6636166e-3],[0.4573116]]
    Value: 0.38285023
    Weights: [[0.92885023,-0.79850036,-1.1552118,1.1241881],[-0.29894832,-0.2826973],[-0.3822282,4.766236e-2],[0.38285023]]
    Value: 0.409146
    Weights: [[0.9125361,-0.7355451,-1.16314,1.1857696],[-0.2968727,-0.23292847],[-0.34678996,0.10931795],[0.409146]]
    Value: 0.3861534
    Weights: [[0.9074217,-0.50569546,-1.1667498,1.3334413],[-0.29494518,-0.20106566],[-0.3378572,0.20942613],[0.3861534]]
    Value: 0.37474877
    Weights: [[0.881248,-0.16207333,-1.17883,1.4279035],[-0.3065645,-0.22071512],[-0.30104303,0.24967328],[0.31557745]]
    Value: 0.36901563
    Weights: [[0.83121735,8.9289926e-2,-1.188469,1.4317765],[-0.34764448,-0.28240365],[-0.20207496,0.26828957],[0.27436042]]
    Value: 0.34190178
    Weights: [[0.8073399,0.3055273,-1.1929594,1.4152205],[-0.36781844,-0.36489633],[-0.1504482,0.31136447],[0.21266654]]
    Value: 0.39675134
    Weights: [[0.7917555,0.5671511,-1.1955255,1.3983365],[-0.38343543,-0.36191055],[-0.121885896,0.3676125],[0.17823151]]
    Value: 0.40246856
    Weights: [[0.7864455,0.6904418,-1.1960931,1.3722917],[-0.38831383,-0.3520135],[-0.10560625,0.3851921],[0.14045607]]
    END SESS 1: 0.40246856
    SESS 1 Weights: [[0.7864455,0.6904418,-1.1960931,1.3722917],[-0.38831383,-0.3520135],[-0.10560625,0.3851921],[0.14045607]]
    SESS 2 Weights: [[0.7864455,0.6904418,-1.1960931,1.3722917],[-0.38831383,-0.3520135],[-0.10560625,0.3851921],[0.14045607]]
    START SESS 2: 0.40246856
    Value: 0.38885224
    Weights: [[0.7864455,0.6652726,-1.1960931,1.3471189],[-0.38831383,-0.37718755],[-0.10560625,0.36001816],[0.16299455]]
    Value: 0.39837453
    Weights: [[0.5771329,0.8102075,-1.337519,1.2285916],[-0.59027094,-0.57970697],[-5.775206e-2,0.391446],[0.21092089]]
    Value: 0.4075203
    Weights: [[0.57657003,0.7987674,-1.3378518,1.3187951],[-0.59081763,-0.4528176],[-5.7260357e-2,0.3931838],[0.15830564]]
    Value: 0.41166776
    Weights: [[0.57657003,0.82338893,-1.3378518,1.3403077],[-0.59081763,-0.34017944],[-5.7260357e-2,0.37597418],[0.121296905]]
    Value: 0.40699238
    Weights: [[0.57657003,0.8049346,-1.3378518,1.3679475],[-0.59081763,-0.27098227],[-5.7260357e-2,0.3674185],[9.8489106e-2]]
    Value: 0.4097725
    Weights: [[0.57657003,0.8212424,-1.3378518,1.3632352],[-0.59081763,-0.25264814],[-5.7260357e-2,0.3670097],[9.1385804e-2]]
    Value: 0.41011882
    Weights: [[0.57657003,0.821501,-1.3378518,1.3658354],[-0.59081763,-0.2386231],[-5.7260357e-2,0.36570212],[8.7290965e-2]]
    Value: 0.40840963
    Weights: [[0.57657003,0.826921,-1.3378518,1.3685763],[-0.59081763,-0.20550646],[-5.7260357e-2,0.3633921],[7.380954e-2]]
    Value: 0.40994892
    Weights: [[0.57657003,0.82443625,-1.3378518,1.3735099],[-0.59081763,-0.19147043],[-5.7260357e-2,0.36392176],[6.9667935e-2]]
    Value: 0.4094312
    Weights: [[0.57657003,0.8249445,-1.3378518,1.3740543],[-0.59081763,-0.18609188],[-5.7260357e-2,0.3635956],[6.7291014e-2]]
    Value: 0.41237888
    Weights: [[0.57657003,0.829351,-1.3378518,1.3770052],[-0.59081763,-0.17982017],[-5.7260357e-2,0.36893737],[6.1324734e-2]]
    END SESS 2: 0.41237888

Note that weights and values where session 1 ends and session 2 begins are equal (in the middle of the above output). At this point I am just not sure whether all parameters for the optimizer are stored and restored correctly, but I guess so.

**Comment by rikvdkleij** [comment]
Thanks again!

The point is that I do not see how you save your neural network model to a protobuffer file, restore it and use it to do the prediction with the trained model parameters.
