### ISSUE TITLE
Missing reduceMax

### ISSUE THREAD

**Issue by rschlotterbeck** [tensorflow/haskell#243]
I am trying to implement a global max pooling layer. Basically, a way to find the maxima of a tensor along given axes would suffice (cf. implementation of reduceSum/reduceMean in https://github.com/tensorflow/haskell/blob/7316062c1031fe4cab1bb4e81e285345a30387da/tensorflow-ops/src/TensorFlow/Ops.hs#L326)

**Comment by jcberentsen** [comment]
Maybe https://tensorflow.github.io/haskell/haddock/tensorflow-core-ops-0.2.0.0/TensorFlow-GenOps-Core.html#v:maxPoolV2
is relevant?

The C++ docs has more info:
https://www.tensorflow.org/versions/r1.9/api_docs/cc/class/tensorflow/ops/max-pool-v2

**Comment by fkm3** [comment]
Yeah, there is a max pool operation if that is what you are looking for.

If you actually want `reduceMax`, then there is a `max` op:
https://tensorflow.github.io/haskell/haddock/tensorflow-core-ops-0.2.0.0/TensorFlow-GenOps-Core.html#v:max

You can copy-paste `reduceSum`'s implementation and change `CoreOps.sum'` to `CoreOps.max'` to get a nicer interface.

**Comment by fkm3** [comment]
(also, if you'd like it to be included in `TensorFlow/Ops.hs`, then I'm happy to approve the pull request!)

**Comment by rschlotterbeck** [comment]
Ah, the `max` op should work, thanks a lot! I probably got that one confused with `maximum`. I also didn't know about the haddock page, so that's gonna make things easier.
