### ISSUE TITLE
Reverse-mode automatic differentiation

### ISSUE THREAD

**Issue by johndoe888** [tensorflow/haskell#252]
Seems like my last comment(question) in [this issue](https://github.com/tensorflow/haskell/issues/251) was overseen. 

As stated I would like to use reverse-mode automatic differentiation in the Haskell Tensorflow bindings. In my tests in TensorFlow 1.14 the GradientTape was usable and did not require eager mode execution. 

Maybe you can explain in a little more detail why this is not usable via Haskell?
Can I be of help in implementing support for this feature?

**Comment by blackgnezdo** [comment]
Reopening the original instead.
