### ISSUE TITLE
Why is tensorflow-mnist-input-data not on Hackage?

### ISSUE THREAD

**Issue by mikesperber** [tensorflow/haskell#260]
More a question than an issue - this complicates the Nix derivations for the Tensorflow stuff somewhat. 

See here:

https://github.com/NixOS/nixpkgs/pull/88604#issuecomment-633755951

If there's an easy way to put in on Hackage, it'd be great if that could happen.

**Comment by blackgnezdo** [comment]
The reason this is a separate package at all is due to the uncertain licensing status of the data files it downloads. If somebody could get a license clarification from Yann LeCun, things would be so much easier.

**Comment by mikesperber** [comment]
@blackgnezdo I'd be happy to contact him, but Wikipedia (and other software packages that contain these files) state a CC license:

https://en.wikipedia.org/wiki/MNIST_database

Isn't that enough?

**Comment by blackgnezdo** [comment]
I don't see any licensing statement in the wikipedia page (the only match for "license" is at the bottom and I think it pertains to the wikipedia article). Ideally the license grant should be on the distribution page: http://yann.lecun.com/exdb/mnist/

**Comment by fkm3** [comment]
Have you considered excluding `tensorflow-mnist` from the nix pkg? I'm not sure example projects like `tensorflow-mnist` make much sense on hackage, I only uploaded it by accident and there doesn't seem to be a way to delete it.

**Comment by mikesperber** [comment]
@blackgnezdo Sorry, I goofed on the Wikipedia page. This definitely has a license statement:

http://www.pymvpa.org/datadb/mnist.html

I'll contact LeCunn also.

(I agree that it shouldn't necessarily be a Nix package, but somebody put it in in the distant past, and I'd rather not break its users.)
