### ISSUE TITLE
Fail on Debian Build

### ISSUE THREAD

**Issue by burne251** [tensorflow/haskell#262]
Hi, 
I've got the standard tensorflow working fine, as well as the rocm branch. Cabal failed to install tensorflow haskell, so I attempted to build from both the github repo and the release tarball using the latest Stack available (2.3.1). The fail error is below.
`tensorflow-proto   > configure (lib)
tensorflow-proto   > Configuring tensorflow-proto-0.2.0.1...
            
Warning: Wildcard does not match any files: third_party/tensorflow/tensorflow/core/example/*.proto 
         in directory: /home/burne251/haskell/tensorflow-proto/
            
Warning: Wildcard does not match any files: third_party/tensorflow/tensorflow/core/framework/*.proto 
         in directory: /home/burne251/haskell/tensorflow-proto/
            
Warning: File listed in tensorflow-proto/tensorflow-proto.cabal file does not exist: third_party/tensorflow/tensorflow/core/lib/core/error_codes.proto
            
Warning: Wildcard does not match any files: third_party/tensorflow/tensorflow/core/protobuf/*.proto 
         in directory: /home/burne251/haskell/tensorflow-proto/
            
Warning: Wildcard does not match any files: third_party/tensorflow/tensorflow/core/util/*.proto 
         in directory: /home/burne251/haskell/tensorflow-proto/
tensorflow-proto   > build (lib)
tensorflow-proto   > setup: filepath wildcard
tensorflow-proto   > 'third_party/tensorflow/tensorflow/core/example/*.proto' refers to the
tensorflow-proto   > directory 'third_party/tensorflow/tensorflow/core/example', which does not
tensorflow-proto   > exist or is not a directory.
tensorflow-proto   > 
            
Warning: Wildcard does not match any files: third_party/tensorflow/tensorflow/core/example/*.proto 
         in directory: /home/burne251/haskell/tensorflow-proto/
            
Warning: Wildcard does not match any files: third_party/tensorflow/tensorflow/core/framework/*.proto 
         in directory: /home/burne251/haskell/tensorflow-proto/
            
Warning: File listed in tensorflow-proto/tensorflow-proto.cabal file does not exist: third_party/tensorflow/tensorflow/core/lib/core/error_codes.proto
            
Warning: Wildcard does not match any files: third_party/tensorflow/tensorflow/core/protobuf/*.proto 
         in directory: /home/burne251/haskell/tensorflow-proto/
            
Warning: Wildcard does not match any files: third_party/tensorflow/tensorflow/core/util/*.proto 
         in directory: /home/burne251/haskell/tensorflow-proto/
            
--  While building package tensorflow-proto-0.2.0.1 using:
      /home/burne251/haskell/tensorflow-proto/.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.0.1.0/setup/setup --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.0.1.0 build lib:tensorflow-proto --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
Progress 1/7`

Any ideas? Just trying to get it working with rocm on a Debian install.

**Comment by fkm3** [comment]
I'd guess that the rocm branch of tensorflow is based is on a newer version than we support. We don't support tensorflow 2.0 or newer yet.

**Comment by blackgnezdo** [comment]
We do now support newer TF per #267. See if that helps at all?
