### ISSUE TITLE
Package won't install.

### ISSUE THREAD

**Issue by skynet1** [tensorflow/haskell#264]
The package won't install when I run "cabal install tensorflow"
It gives this error:

Resolving dependencies...
Build profile: -w ghc-8.6.5 -O1
In order, the following will be built (use -v for more details):
 - proto-lens-protobuf-types-0.5.0.0 (lib:proto-lens-protobuf-types) (requires build)
 - tensorflow-proto-0.2.0.1 (lib:tensorflow-proto) (requires build)
 - tensorflow-0.2.0.1 (lib) (requires build)
Starting     proto-lens-protobuf-types-0.5.0.0 (all, legacy fallback)
Building     proto-lens-protobuf-types-0.5.0.0 (all, legacy fallback)

Failed to build proto-lens-protobuf-types-0.5.0.0.
Build log (
/home/noah/.cabal/logs/ghc-8.6.5/proto-lens-protobuf-types-0.5.0.0-790cb4789ed050fbe466d3816407d2cc31cb4028416a0d504828a8cb7248cdaa.log
):
[1 of 1] Compiling Main             ( /tmp/cabal-install.-22292/dist-newstyle/tmp/src-22292/proto-lens-protobuf-types-0.5.0.0/dist/setup/setup.hs, /tmp/cabal-install.-22292/dist-newstyle/tmp/src-22292/proto-lens-protobuf-types-0.5.0.0/dist/setup/Main.o )
Linking /tmp/cabal-install.-22292/dist-newstyle/tmp/src-22292/proto-lens-protobuf-types-0.5.0.0/dist/setup/setup ...
Configuring proto-lens-protobuf-types-0.5.0.0...
Preprocessing library for proto-lens-protobuf-types-0.5.0.0..
Building library for proto-lens-protobuf-types-0.5.0.0..
[ 1 of 12] Compiling Paths_proto_lens_protobuf_types ( dist/build/autogen/Paths_proto_lens_protobuf_types.hs, dist/build/Paths_proto_lens_protobuf_types.o )
[ 2 of 12] Compiling Proto.Google.Protobuf.Any ( dist/build/autogen/Proto/Google/Protobuf/Any.hs, dist/build/Proto/Google/Protobuf/Any.o )

dist/build/autogen/Proto/Google/Protobuf/Any.hs:63:3: error:
    ‘packedMessageDescriptor’ is not a (visible) method of class ‘Data.ProtoLens.Message’
   |
63 |   packedMessageDescriptor _
   |   ^^^^^^^^^^^^^^^^^^^^^^^

dist/build/autogen/Proto/Google/Protobuf/Any.hs:68:3: error:
    ‘packedFileDescriptor’ is not a (visible) method of class ‘Data.ProtoLens.Message’
   |
68 |   packedFileDescriptor _ = packedFileDescriptor
   |   ^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build proto-lens-protobuf-types-0.5.0.0 (which is required by
tensorflow-0.2.0.1). See the build log above for details.

OS is Arch Linux
tensorflow version is 2.3.0
cabal version is 3.2.0.0
and ghc version is 8.6.5

**Comment by blackgnezdo** [comment]
https://github.com/tensorflow/haskell/commit/568c9b6f03e5d66a25685a776386e2ff50b61aa9 may have a fix for the proto-lens problem. Note though that we only ever made tensorflow v1
to work. Your version 2.3.0 is expected to be broken.

**Comment by blackgnezdo** [comment]
Check if #267 made this work?
