### ISSUE TITLE
Tensorflow 2.9 Compatibility

### ISSUE THREAD

**Issue by sheepforce** [tensorflow/haskell#278]
I am trying to get tensorflow bindings working in my Haskell project, that due to its complex dependencies is mainly built with Nix. In #277 I've started to write some Nix for this repo, but it seems that the 2.9 release of Tensorflow is not supported yet, correct?

What would be needed to get it compatible?

**Comment by blackgnezdo** [comment]
[This commit](https://github.com/tensorflow/haskell/commit/c66c912c327810796b6282ae77c33e336c1dadea) switched us to TF-2.3.0. Hopefully something similar to this will get you to 2.9. If you do the upgrade, we'll merge it.
