### ISSUE TITLE
Nvidia (3000 series) Ampere Architecture Support - Update TensorFlow to v2.4.0

### ISSUE THREAD

**Issue by larsvansoest** [tensorflow/haskell#280]
Support for Ampere architectures [was added in TensorFlow v2.4.0](https://github.com/tensorflow/tensorflow/releases/tag/v2.4.0). This architecture is used by Nividia's 3000 series. 

Currently, this project supports up to TensorFlow version v2.3.0. As a result, attempting to run on a 3000 series GPU results in an error mentioned in https://github.com/tensorflow/tensorflow/issues/41990. Moreover, as stated by https://github.com/tensorflow/tensorflow/issues/41990#issuecomment-670224813, the error is raised due to an unsupported graphics card.

To support 3000 series graphics cards for TensorFlow in Haskell, the supported version should be upgraded to at least  [v2.4.0](https://github.com/tensorflow/tensorflow/releases/tag/v2.4.0).

**Comment by larsvansoest** [comment]
Apparently, [this commit in January](https://github.com/tensorflow/haskell/commit/5b77096247f0a70630cba1f33fa56ed748aa1668) bumped the version to 2.10.1.

**Comment by fkm3** [comment]
Yeah, we support newer TF versions now. Let us know if there is still an issue with newer GPUs.
