### ISSUE TITLE
Docker is required, why?

### ISSUE THREAD

**Issue by angerman** [tensorflow/haskell#4]
The readme says 

> For now docker is required

but doesn't state the underlying reason.

Could this be added to the readme?

**Comment by ElvishJerricco** [comment]
Looking at [the Dockerfile](https://github.com/tensorflow/haskell/blob/master/docker/Dockerfile), I think Docker is a little heavy duty for the requirements. Could easily achieve this with Nix, which stack also integrates great with.

**Comment by WillSewell** [comment]
But Docker is in much wider use than Nix.

**Comment by ElvishJerricco** [comment]
True. But I think the Haskell community uses Nix more than Docker. Could be wrong on that, but it's the impression that I get.

**Comment by gleber** [comment]
Docker was the easiest way to get this code out in open and make it easy to build, so others can use it. Feel free to send a PR to include a Nix files required to build this project.

**Comment by blackgnezdo** [comment]
Like @gleber said, starting from the tensorflow docker image was a quick and sure way to get things running. I doubt reimplementing this process in Nix would be productive (e.g. I couldn't find Nix package for TensorFlow).

It would make more sense to document the steps for installing everything on a clean Linux system (whatever that means). Then again, that's what the docker files already do in executable form.

**Comment by blackgnezdo** [comment]
OK, I do see TensorFlow Nix packages. Still, version tracking would be harder this way.

**Comment by ElvishJerricco** [comment]
Why would version tracking be way harder?

**Comment by blackgnezdo** [comment]
Nightly builds of TF docker images are readily available, so one fewer levels of indirection. It's not "way harder", just "harder this way".
