### ISSUE TITLE
Building .dylib on osx?

### ISSUE THREAD

**Issue by o1lo01ol1o** [tensorflow/haskell#42]
The build instructions for osx produce a shared object `.so` file but this extension is not resolved by stack when trying to link the tensorflow project as a local dependency.  (It looks like the `.so` format may not play nicely with stack on osx.)  Is there a way to create a `.dylib` target and build that instead?  References [here](http://stackoverflow.com/questions/40713673/force-stack-to-look-for-so-files-instead-of-dylib-on-os-x) and [here](https://github.com/commercialhaskell/stack/issues/2798)

**Comment by judah** [comment]
Sorry, it looks like I missed a step in the README.  It's enough to just symlink the `.so` file to the `.dylib`, though for some reason it only works if *both* files are present.

I've sent out #43 to update the build instructions.
