### ISSUE TITLE
Specifying and training networks in haskell?

### ISSUE THREAD

**Issue by rbharath** [tensorflow/haskell#59]
Is it possible to specify and train networks through the Haskell API? For example, is the current API mature enough to implement something analogous to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/mnist/mnist_softmax.py? If not, what would be required to get there and can contributors aid the effort?

(My apologies if this question isn't suitable for an issue. I'm glad to ask on a better location in that case)

**Comment by fkm3** [comment]
Yeah, you can both specify and train networks. We have a example of a similar network for mnist here: https://github.com/tensorflow/haskell/blob/master/tensorflow-mnist/app/Main.hs

Contributions are certainly welcomed. Feel free to ask questions.

**Comment by rbharath** [comment]
@fkm3 Thanks for pointer! Will go ahead and close this issue then.
