### ISSUE TITLE
Basic examples

### ISSUE THREAD

**Issue by mohanr** [tensorflow/haskell#64]
I am interested in combining Haskell UI( Spock ? ) and TensorFlow to start working on an image identification system. Identify one image in a group.
Is there a bootstrap example like that ?  Either your example or something TensorFlow has that you referred.

SInce both Haskell and Deep Learning have a very steep learning curve I think we need some basic examples.

**Comment by blackgnezdo** [comment]
Does RegressionTest example introduced in #60 help? It's also included into README.md.

**Comment by mohanr** [comment]
Let me try that for now.
