### ISSUE TITLE
Upload to Hackage

### ISSUE THREAD

**Issue by ocramz** [tensorflow/haskell#66]
The Apache license is liberal enough for the package to be listed on Hackage (the central repository for Haskell libraries) : https://hackage.haskell.org/

**Comment by blackgnezdo** [comment]
We agree it would be nice to publish these packages. Trouble is the complicated build system and a complex state required to be on the system before our build can succeed. Things may improve somewhat once there's TensorFlow 1.0 release. It may still be non-trivial though if the .proto files are not included into the package. Maybe we can package these ourselves then?

**Comment by judah** [comment]
Agreed; I filed google/proto-lens/#69 to figure out a way to include the generated proto modules in the releases on Hackage/Stackage.

**Comment by blackgnezdo** [comment]
Change #69 just got us one step closer to this.

**Comment by rbharath** [comment]
Just wanted to ping this thread. Anything contributors can do to help get it on to hackage?

**Comment by blackgnezdo** [comment]
@rbharath try to do it? @judah do you recall which steps remained?

**Comment by rbharath** [comment]
Willing to give it a shot, but I'm a haskell newbie myself, so no guarantees of success :-)

**Comment by judah** [comment]
As far as I know, there's no hard blockers to uploading the libraries on Hackage.

I had been planning to wait to upload them until I fixed the memory safety issue #92 (probably by switching all of `tensorflow-ops` to resource-based variables, which will also change its API).  However, I won't get to that for at least another week or two, so I have no strong objection to them being uploaded in the meantime.

**Comment by judah** [comment]
So I took an initial look at this...we currently have 14 different packages in our repository:
https://github.com/tensorflow/haskell/blob/master/stack.yaml#L4
All of them would be reasonable to upload to Hackage, with the possible exception of `tensorflow-mnist` and `tensorflow-mnist-input-data`.

This situation feels unwieldy, and it will be tedious to upload and maintain them.  I think it's worth merging some of them, especially the smaller ones where separation doesn't reduce the amount of dependencies needed in practice.  One proposal:
- Merge 'tensorflow-queue' and 'tensorflow-nn' (and maybe also 'tensorflow-logging') into 'tensorflow-ops'.
- Merge 'tensorflow-proto' and 'tensorflow-opgen' into 'tensorflow'
- Possibly remove 'google-shim' altogether, and/or merge it into 'tensorflow-test' (and maybe also find a substitute for the latter)

Thoughts?  Any strong opinions one way or the other?

**Comment by fkm3** [comment]
No objections from me.

**Comment by judah** [comment]
OK, I've uploaded everything to Hackage except the mnist packages, since they have a data dependency and I think are intended more as example code.

I re-uploaded the `tensorflow` package at v0.1.0.1 due to a bug in the `.cabal` file.  Everything else is at `v0.1.0.0`.

Further work on consolidating the packages can be tracked in #112.
