### ISSUE TITLE
Control flow api is a bit opaque

### ISSUE THREAD

**Issue by o1lo01ol1o** [tensorflow/haskell#72]
I've perused the python source and I believe I follow most of the dataflow concepts surrounding `exit`, `enter`, `merge`, `swtich`, `nextIteration`, etc, but I don't understand how they correspond to what is currently exposed in the haskell api. Are there some code/examples/docs somewhere?  How does one get access to frames or their names?

**Comment by fkm3** [comment]
The ops you are looking for are in `TensorFlow-GenOps-Core`, e.g. https://tensorflow.github.io/haskell/haddock/tensorflow-core-ops-0.1.0.0/TensorFlow-GenOps-Core.html#v:enter.

I'm not sure what the plan for the `TensorFlow.ControlFlow` module is.

**Comment by o1lo01ol1o** [comment]
Thanks for the reply.  I'd seen those modules but my question was more toward how they're used.  For example, the docs refer to `frame_name`, `parallel_iterations`, etc but those named parameters are used nowhere that I can find in the API and are only mentioned in the `enter` and `exit` ops.  In python, they're handed as named parameters to classes that track the various iteration contexts.  How are they used in the Haskell api?

**Comment by blackgnezdo** [comment]
We never tried to use these thus the API is raw. You can see these attributes in
[the generated code](https://tensorflow.github.io/haskell/haddock/tensorflow-core-ops-0.1.0.0/src/TensorFlow-GenOps-Core.html#enter). From there one could use
[tensorAttr](https://tensorflow.github.io/haskell/haddock/tensorflow-0.1.0.0/TensorFlow-Tensor.html#v:tensorAttr) to supply the attributes.

Let us know what you build out of this. This should shape the eventual API.

**Comment by o1lo01ol1o** [comment]
Gotcha, that's what I suspected.  I was missing `tensorAttr`.  Thanks for the info, I'll PR if I build something (re)usable.
